// URL Prefixes
export const URL_CONST = {
    URL_PREFIX: 'http://localhost:3334/',
    DEV_PREFIX: 'http://dev.sc-platform.api.reactive-solutions.xyz/',
    DEV_PREFIX_R: 'http://localhost:8000/',
    BACK_END_HOST: 'http://localhost:3000/'
};

export const FUEL_TYPE: Array<any> = [{ "text": "Petrol" }, { "text": "Diesel" }, { "text": "Hybrid" }, { "text": "Gas" }, { "text": "Other" }];

export const TRANSMISSION: Array<any> = [
    { label: 'Automatic', value: 'A', autoSelected: true },
    { label: 'Manual', value: 'M', autoSelected: false },
    { label: 'Tiptronic', value: 'T', autoSelected: false },
    { label: 'Other', value: 'O', autoSelected: false }];


export const VECHICLE_BRANDS: Array<any> = [
    { value: "Abarth", text: "Abarth" },
    { value: "Acura", text: "Acura" },
    { value: "AlfaRomeo", text: "AlfaRomeo" },
    { value: "Ambassador", text: "Ambassador" },
    { value: "Aprilia", text: "Aprilia" },
    { value: "Audi", text: "Audi" },
    { value: "Austin", text: "Austin" },
    { value: "Bajaj", text: "Bajaj" },
    { value: "BMW", text: "BMW" },
    { value: "Chery", text: "Chery" },
    { value: "Chevrolet", text: "Chevrolet" },
    { value: "Chrysler", text: "Chrysler" },
    { value: "Citroen", text: "Citroen" },
    { value: "Daewoo", text: "Daewoo" },
    { value: "Daihatsu", text: "Daihatsu" },
    { value: "DFSK", text: "DFSK" },
    { value: "Dimo", text: "Dimo" },
    { value: "DskBenelli", text: "DskBenelli" },
    { value: "DTM", text: "DTM" },
    { value: "Ducati", text: "Ducati" },
    { value: "FAW", text: "FAW" },
    { value: "Fiat", text: "Fiat" },
    { value: "Ford", text: "Ford" },
    { value: "Foton", text: "Foton" },
    { value: "HarleyDavidson", text: "HarleyDavidson" },
    { value: "HeroHonda", text: "HeroHonda" },
    { value: "Honda", text: "Honda" },
    { value: "Hummer", text: "Hummer" },
    { value: "Hyundai", text: "Hyundai" },
    { value: "Isuzu", text: "Isuzu" },
    { value: "Jaguar", text: "Jaguar" },
    { value: "Jeep", text: "Jeep" },
    { value: "Jialing", text: "Jialing" },
    { value: "JMC", text: "JMC" },
    { value: "Kawasaki", text: "Kawasaki" },
    { value: "Kia", text: "Kia" },
    { value: "Kinetic", text: "Kinetic" },
    { value: "Komatsu", text: "Komatsu" },
    { value: "Ktm", text: "Ktm" },
    { value: "Lancia", text: "Lancia" },
    { value: "LandRover", text: "LandRover" },
    { value: "Lexus", text: "Lexus" },
    { value: "Leyland", text: "Leyland" },
    { value: "Mahindra", text: "Mahindra" },
    { value: "MarutiSuzuki", text: "MarutiSuzuki" },
    { value: "Mazda", text: "Mazda" },
    { value: "Mercedes-Benz", text: "Mercedes-Benz" },
    { value: "Micro", text: "Micro" },
    { value: "MINI", text: "MINI" },
    { value: "Mitsubishi", text: "Mitsubishi" },
    { value: "MorrisGarage", text: "MorrisGarage" },
    { value: "Nissan", text: "Nissan" },
    { value: "Opel", text: "Opel" },
    { value: "Perodua", text: "Perodua" },
    { value: "Peugeot", text: "Peugeot" },
    { value: "Porsche", text: "Porsche" },
    { value: "Proton", text: "Proton" },
    { value: "Renault", text: "Renault" },
    { value: "Rover", text: "Rover" },
    { value: "RoyalEnfield", text: "RoyalEnfield" },
    { value: "Simca", text: "Simca" },
    { value: "Skoda", text: "Skoda" },
    { value: "Ssangyong", text: "Ssangyong" },
    { value: "Subaru", text: "Subaru" },
    { value: "Suzuki", text: "Suzuki" },
    { value: "Tata", text: "Tata" },
    { value: "Tesla", text: "Tesla" },
    { value: "ThaiRungUnion", text: "ThaiRungUnion" },
    { value: "Toyota", text: "Toyota" },
    { value: "Triumph", text: "Triumph" },
    { value: "Tvs", text: "Tvs" },
    { value: "Vauxhall", text: "Vauxhall" },
    { value: "Volkswagen", text: "Volkswagen" },
    { value: "Volvo", text: "Volvo" },
    { value: "Willys", text: "Willys" },
    { value: "Yamaha", text: "Yamaha" },
    { value: "Zotye", text: "Zotye" }];



export const VECHICLE_BRANDS_OLD: Array<any> = [
    { value: "1", text: "Abarth" },
    { value: "3", text: "Acura" },
    { value: "7", text: "AlfaRomeo" },
    { value: "1533", text: "ambassador" },
    { value: "24", text: "Aprilia" },
    { value: "30", text: "Audi" },
    { value: "64", text: "Austin" },
    { value: "68", text: "Bajaj" },
    { value: "78", text: "BMW" },
    { value: "108", text: "Chery" },
    { value: "116", text: "Chevrolet" },
    { value: "1501", text: "Chrysler" },
    { value: "131", text: "Citroen" },
    { value: "153", text: "Daewoo" },
    { value: "162", text: "Daihatsu" },
    { value: "1509", text: "DFSK" },
    { value: "178", text: "Dimo" },
    { value: "182", text: "DskBenelli" },
    { value: "1575", text: "DTM" },
    { value: "184", text: "Ducati" },
    { value: "1538", text: "FAW" },
    { value: "193", text: "Fiat" },
    { value: "227", text: "Ford" },
    { value: "294", text: "Foton" },
    { value: "296", text: "HarleyDavidson" },
    { value: "309", text: "HeroHonda" },
    { value: "321", text: "Honda" },
    { value: "1558", text: "Hummer" },
    { value: "376", text: "Hyundai" },
    { value: "404", text: "Isuzu" },
    { value: "429", text: "Jaguar" },
    { value: "460", text: "Jeep" },
    { value: "494", text: "Jialing" },
    { value: "1573", text: "JMC" },
    { value: "499", text: "Kawasaki" },
    { value: "524", text: "Kia" },
    { value: "544", text: "Kinetic" },
    { value: "1561", text: "Komatsu" },
    { value: "546", text: "Ktm" },
    { value: "552", text: "Lancia" },
    { value: "556", text: "LandRover" },
    { value: "575", text: "Lexus" },
    { value: "605", text: "Leyland" },
    { value: "607", text: "Mahindra" },
    { value: "627", text: "MarutiSuzuki" },
    { value: "643", text: "Mazda" },
    { value: "690", text: "Mercedes-Benz" },
    { value: "905", text: "Micro" },
    { value: "924", text: "MINI" },
    { value: "927", text: "Mitsubishi" },
    { value: "967", text: "MorrisGarage" },
    { value: "969", text: "Nissan" },
    { value: "1020", text: "Opel" },
    { value: "1028", text: "Perodua" },
    { value: "1037", text: "Peugeot" },
    { value: "1062", text: "Porsche" },
    { value: "1082", text: "Proton" },
    { value: "1099", text: "Renault" },
    { value: "1120", text: "Rover" },
    { value: "1126", text: "RoyalEnfield" },
    { value: "1138", text: "Simca" },
    { value: "1141", text: "Skoda" },
    { value: "1148", text: "Ssangyong" },
    { value: "1156", text: "Subaru" },
    { value: "1172", text: "Suzuki" },
    { value: "1208", text: "Tata" },
    { value: "1581", text: "Tesla" },
    { value: "1234", text: "ThaiRungUnion" },
    { value: "1236", text: "Toyota" },
    { value: "1339", text: "Triumph" },
    { value: "1354", text: "Tvs" },
    { value: "1376", text: "Vauxhall" },
    { value: "1380", text: "Volkswagen" },
    { value: "1408", text: "Volvo" },
    { value: "1440", text: "Willys" },
    { value: "1454", text: "Yamaha" },
    { value: "1514", text: "Zotye" }];

export const VECHICLE_CONDITIONS: Array<any> = [{ text: "New", value: "N" }, { text: "Used", value: "U" }, { text: "Reconditioned", value: "R" }];


