export const DUMMY_VECHICLE_LIST: Array<any> = [{
    id: '1001',
    brand: 'Toyota',
    vechicleModel: 'Axio Hybrid',
    transmission: 'Auto',
    vtype: 'Car',
    condition: 'Used',
    modelYear: '2014',
    mileAge: '17890 km',
    price: '4.3 millions',
    priceNegotiable: 'Y',
    fuelType: 'demo-text',
    fuelTypes: ['H', 'P'],
    contact: { name: 'Dr.Peter James', place: 'colombo-09', phone: '077-xxx-ccc-gfs' },
    imgUrl: 'http://www.copyright-free-photos.org.uk/cars/mini-cooper.jpg'
}, {
    id: '1002',
    brand: 'demo-brand-2',
    vechicleModel: 'demo-model',
    transmission: 'manual',
    vtype: 'demo-text',
    condition: 'demo-text',
    modelYear: 'demo-text',
    mileAge: 'demo-text',
    price: 'demo-text',
    priceNegotiable: 'N',
    fuelType: 'demo-text',
    fuelTypes: ['H', 'P'],
    contact: { name: 'itsme call me', place: 'colombo-04', phone: '077-xxx-ccc-gfs' },
    imgUrl: 'http://www.copyright-free-photos.org.uk/cars/silver-shadow.jpg'
},
{
    id: '1001',
    brand: 'Toyota',
    vechicleModel: 'Axio Hybrid',
    transmission: 'Auto',
    vtype: 'Car',
    condition: 'Used',
    modelYear: '2014',
    mileAge: '17890 km',
    price: '4.3 millions',
    priceNegotiable: 'Y',
    fuelType: 'demo-text',
    fuelTypes: ['H', 'P'],
    contact: { name: 'Dr.Peter James', place: 'colombo-09', phone: '077-xxx-ccc-gfs' },
    imgUrl: 'http://www.copyright-free-photos.org.uk/cars/mini-cooper.jpg'
}, {
    id: '1002',
    brand: 'demo-brand-2',
    vechicleModel: 'demo-model',
    transmission: 'manual',
    vtype: 'demo-text',
    condition: 'demo-text',
    modelYear: 'demo-text',
    mileAge: 'demo-text',
    price: 'demo-text',
    priceNegotiable: 'N',
    fuelType: 'demo-text',
    fuelTypes: ['H', 'P'],
    contact: { name: 'itsme call me', place: 'colombo-04', phone: '077-xxx-ccc-gfs' },
    imgUrl: 'http://www.copyright-free-photos.org.uk/cars/silver-shadow.jpg'
}];
